// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbJPSZ3ArDxWOjIpGufwNoPJQkdAVcJtU',
    appId: '1:530010359092:android:1ad0a72253c1024f9b9161',
    messagingSenderId: '530010359092',
    projectId: 'adsmasetrapi',
    databaseURL: 'https://adsmasetrapi-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'adsmasetrapi.appspot.com',
  );

}